---
title: "Course overview"
subtitle: "International Internship and Special Topics Seminar"
---

## A slightly more detailed overview.

### Course description

This course integrates pedagogical and theoretical concepts related to teaching and learning in an international context. Candidates will develop global competencies and teaching skills via exposure to international students and educational environments. The seminar aspect of the course will employ online discussions, journal writing, and interdisciplinary readings to enrich the cross-cultural experiences and facilitate the intercultural development of teacher candidates. Candidates in the Elementary Education Program are eligible to register for 9 credit hours.

### **Syllabus**

A high-level view of the course.

*Please note: this section is only a summary of our syllabus.* The full syllabus is available on our Canvas site [here](https://canvas.howard.edu/courses/58654/){target="_blank"}. I have summarized some important items found on the syllabus below:

**Instructor**: Nathan Alexander, PhD

-   Contact information:

    **Email**: [nathan.alexander\@howard.edu](mailto:nathan.alexander@howard.edu)

    **Office hours**: By appointment at <https://nathanalexander.youcanbook.me>

-   Course information:

    **Course meeting times**: Tuesdays, 5:10pm - 7:30pm EST

    **Course meeting location**: Miner Building 211

### **Canvas**

Canvas is the go-to for submissions, and where you can find readings and assignment rubrics. [Here](https://canvas.howard.edu/courses/58654/) is another link to Canvas, I'll try to drop these as often as possible. Two things about Canvas: it has your **assignments** and it has your **readings**.

#### Canvas has your course assignments

::: incremental
The four categories for **assignments** in this course are as follows:

-   **Reflection and readings** \[20 points\]
-   **International trip assignments** \[20 points\]
-   **Lesson/unit plan and presentations** \[40 points\]
-   **Field placement log and excursions** \[20 points\]
:::

### **A few other items**

#### Expectations

This course will help you gain both a conceptual and theoretical understanding of the various concepts we will explore, and then a technical understanding of the complex issues that relate to them. We also want to communicate our ideas. These can be difficult tasks. But I encourage you to explore and to be creative, and to take chances. Errors should mostly remind us that there is always the backspace button. Below are some general **expectations** to keep us all moving forward as a community:

::: incremental
-   Communicate early and often
-   Show up to class on time
-   Do not schedule other meetings during class time
-   No late work will be accepted without prior discussion
:::

### **Course site** (this page!)

You can return to this page to remind yourself of the four parts of our course, especially when we dive deep into specific projects. This page will remain static (it will not be updated), so use it as an archive that you can return to; start in this page position if you have questions about the schedule, procedures, expectations (above) ...then assignments (next).
